---
- name: Install Grafana
  hosts: main
  remote_user: ubuntu
  become: true
  vars:
    - ansible_ssh_common_args: "-o StrictHostKeyChecking=accept-new"
 
  tasks: 

    - name: install aptitude 
      apt:
        name: aptitude
        state: latest
        update_cache: true
    - name: apt-get update
      ansible.builtin.apt:
        update_cache: yes  
    - name: install required packages
      apt:
        pkg:
          - apt-transport-https
          - software-properties-common
          - libfontconfig1
        state: latest
        update_cache: true
      
    - name: download apt key
      ansible.builtin.apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present
    - name: Add grafana to sources.list
      ansible.builtin.apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
        filename: grafana
        state: present
    - name: Update apt cache and install Grafana
      ansible.builtin.apt: 
        name: grafana
        update_cache: yes
    - name: Ensure Grafana is started and enabled
      ansible.builtin.systemd:
        name: grafana-server
        enabled: yes
        state: started
